### ISSUE TITLE
Crash when using mods like "Elytra Trinket"

### ISSUE THREAD

**Issue by RedstoneTrail** [jewtvet/elytrahud#1]
I have found that, when activating an elytra and a mod like "Elytra Trinket" ([](https://modrinth.com/mod/elytra_trinket)), or "Elytra Slot" ([](https://modrinth.com/mod/elytra-slot)), which provide a trinket slot to wear elytras in, the game crashes. This does not happen unless the elytra is in the additional elytra slot.

**Comment by jewtvet** [comment]
Thanks for the issue! Fixed it in 1.0.2 version: [Modrinth](https://modrinth.com/mod/elytra-hud/version/1.0.2) / [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/elytra-hud-like-mfs-2020/files/5002608)
Please give a callback is it fixed
