### ISSUE TITLE
Enabling hud without flight

### ISSUE THREAD

**Issue by noviceThelizard** [jewtvet/elytrahud#2]
Is there any way to enable the hud without flying? 
it would be nice to also be able to use it on the ground

**Comment by jewtvet** [comment]
Hi, I’ve many ideas of mods that will use similar (or not) indicators for horse, pig, boat and minecart. As for me, boat hud from NFS Most Wanted 2005 is really cool idea, but next 1-2 moths I will have a lot of work, so I think they will be coded later :(

**Comment by boboiq** [comment]
Please tell me how to make the HUD always on if you don’t want to bother with the switch. Your mod is very convenient for servers with planes, but it only works on elytras, this is not convenient.
