### ISSUE TITLE
Request for 1.21 update

### ISSUE THREAD

**Issue by Kishku7** [jewtvet/elytrahud#4]
I loved this mod, and playing without it is driving me nuts.

Are there any incentives I could offer to get you to update this mod?

**Comment by jewtvet** [comment]
Yes, 1.20.6 and 1.21 are in plans. Hope, will find time to do it in 1-2 weeks

**Comment by jewtvet** [comment]
updated to 1.21
https://modrinth.com/mod/elytra-hud/version/1.1.0
